name: Build and Deploy for Github Pages
on:
  workflow_dispatch:
  push:
    paths:
      - "src/**"
      - "packages/**"
      - "apps/**"
      - "public/**"
      - ".github/workflows/**"
      - "package.json"
      - "vite.config.ts"
      - "vite.config.js"
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 🛑 Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.6.0
        with:
          access_token: ${{ secrets.GITHUB_TOKEN }}

      - name: ⬇️ Checkout repo
        uses: actions/checkout@v3

      - name: ⎔ Setup bun
        uses: oven-sh/setup-bun@v2

      - name: Install
        run: bun install

      - name: ⚙️ Build
        run: bun run build

      - name: ⚙️ Setup Pages
        if: success()
        uses: actions/configure-pages@v3

      - name: 📁 Upload artifact
        if: success()
        uses: actions/upload-pages-artifact@v3
        with:
          # Upload entire repository
          path: "./dist"

  deploy:
    # Add a dependency to the build job
    needs: build

    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write # to deploy to Pages
      id-token: write # to verify the deployment originates from an appropriate source

    # Allow one concurrent deployment
    concurrency:
      group: "pages"
      cancel-in-progress: true

    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    # Specify runner + deployment step
    runs-on: ubuntu-latest
    steps:
      - name: 🚀 Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
